apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-api
  name: users-api
spec:
  selector:
    matchLabels:
      app: users-api
  replicas: 1
  template:
    metadata:
      labels:
        app: users-api
        service: users-api
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        image: akshaycgnlxdevops/users-api
        name: users-api
        ports:
        - containerPort: 8083
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
