apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: zipkin
  type: LoadBalancer
