apiVersion: v1
kind: Service
metadata:
  name: {{ template "node-todo.redisqueue.fullname" . }}
  labels:
    {{- include "node-todo.redisqueue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redisqueue.service.type }}
  ports:
    - port: {{ .Values.redisqueue.service.port }}
      targetPort: 6379
  selector:
    {{- include "node-todo.redisqueue.matchLabels" . | nindent 4 }}
